import type { Metadata } from "next";
// import { Nunito_Sans } from "next/font/google";

import "./globals.css";

export const metadata: Metadata = {
  title: "FDS Docs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        {children}
      </body>
    </html>
  );
}
